name: Gradle Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: permissions
        run: chmod +x gradlew

      - name: build
        run: ./gradlew build

      - name: copy jar to builds
        run: |
          mkdir -p builds
          cp build/libs/TuffX.jar builds/TuffX.jar

      - name: push jar
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add builds/TuffX.jar
          git commit -m "Update build artifact"
          git push
